workflows:
  ios-app:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "broke.xcodeproj"
        XCODE_SCHEME: "broke"
        APP_STORE_CONNECT: "api_key" # Set this if publishing
    scripts:
      - name: Install dependencies
        script: |
          gem install bundler
          bundle install
      - name: Build the app
        script: |
          xcodebuild -project $XCODE_PROJECT -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release
    artifacts:
      - build/ios/iphoneos/*.app